AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  aws_subscription_project

Globals:
  Function:
    Timeout: 3

Resources:
  SubscribeUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: subscribe_user/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref SubscriptionsTable
      Architectures: 
        - x86_64
      Events:
        SubscribeUser:
          Type: Api
          Properties:
            Path: /subscribe
            Method: get

  SubscriptionsTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: subscriptions
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  SubscribeUserApi:
    Description: "API Gateway URL for SubscribeUser"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/subscribe"
  SubscribeUserFunction:
    Description: "Function ARN for SubscribeUser"
    Value: !GetAtt SubscribeUserFunction.Arn
  SubscribeUserFunctionIamRole:
    Description: "IAM Role ARN for SubscribeUser"
    Value: !GetAtt SubscribeUserFunctionRole.Arn
